services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: notes_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - assignment-network
  backend:
    depends_on:
      - postgres
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      PORT: 3001
      DATABASE_URL: postgresql://user:password@postgres:5432/notes_db
      NODE_ENV: development
    networks:
      - assignment-network
  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://localhost:3001
    networks:
      - assignment-network
volumes:
  postgres_data:
networks:
  assignment-network:
    driver: bridge
